echo "Deleting all files...";
alias find='/cygdrive/c/cygwin/bin/find.exe'
rm allJavaFiles.txt;
rm allControllerBeans.txt;
rm allDelegateFiles.txt;
rm allDAOImpl.txt;
rm allHBMFiles.txt;
rm allJSFiles.txt;
rm allJSPFiles.txt;
rm allPropertiesFiles.txt;
rm allErrorMessages.txt;
rm allFacadeBean.txt;
rm allServiceImpl.txt;
rm allSCAReferences.txt;
rm allBPEL.txt;
echo "Creating all files...";
find . -type f | egrep ".java$" | egrep -vi test > allJavaFiles.txt;
find . -type f | egrep "Bean.java$" | egrep -vi "test|process|facade|data" > allControllerBeans.txt;
find . -type f | egrep "Delegate.java$" | egrep -vi test > allDelegateFiles.txt;
find . -type f | egrep "DAOImpl.java$" | egrep -vi test > allDAOImpl.txt;
find . -type f | egrep ".hbm.xml$" | egrep -vi test > allHBMFiles.txt;
find . -type f | egrep ".js$" | egrep -vi test > allJSFiles.txt;
find . -type f | egrep ".jsp$" | egrep -vi test > allJSPFiles.txt;
find . -type f | egrep "_en.properties$" | egrep -vi test > allPropertiesFiles.txt;
find . -type f | egrep "Messages_en.properties$" | egrep -vi test > allErrorMessages.txt;
find . -type f | egrep "Bean.java$" | egrep -vi "test|controller|view" > allFacadeBean.txt;
find . -type f | egrep "Impl.java$" | egrep -vi "test|DAO" > allServiceImpl.txt;
find . -type f | egrep "sca.references$" | egrep -vi test > allSCAReferences.txt;
find . -type f | egrep ".bpel$" | egrep -vi test > allBPEL.txt;
echo "Files created successfully!!";